name: Deploy to staging
on:
  push:
    branches: [ main ]
jobs:
  redeploy_everything:
     runs-on: ubuntu-latest
     name: Deploying everything to the staging cluster
     steps:
       - run: |
           echo "${{secrets.SSH_PRIVATE_KEY}}" &> ~/ssh_key
           mkdir -p /home/runner/.ssh
           ls /home/runner/.ssh
           touch /home/runner/.ssh/known_hosts
           echo "${{secrets.SSH_KNOWN_HOSTS}}" &> /home/runner/.ssh/
           known_hosts
           chmod700 /home/runner/ssh_key
           ssh -i ~/ssh_key root@64.23.156.135
           cd devops-class25.2/ && git pull 
           pnpm install
           pnpm run build
           pm2 restart fe-server
           pm2 restart ws-server
           pm2 restart http-server